DROP TABLE IF EXISTS pre_header;

CREATE TABLE pre_header (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    full_name TEXT NOT NULL,
    content TEXT NOT NULL
);

DROP TABLE IF EXISTS third_bot;

CREATE TABLE third_bot (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    callback_url TEXT NOT NULL,
    bot_name TEXT NOT NULL,
    token TEXT NOT NULL
);